### ISSUE TITLE
Typo in wiki

### ISSUE THREAD

**Issue by gregoiremenguy** [Quefumas/gensound#22]
Hi,

There is a typo in the [(wiki)](https://github.com/Quefumas/gensound/wiki/Automation). Indeed, `gensound.curves` must be replaced by `gensound.curve` (no ''s'') in the imports.

Best

**Comment by Quefumas** [comment]
Hi @gregoiremenguy,

Thank you for the correction, I appreciate it. Please let me know if you find other mistakes!
